// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzpQKmHJ6bhvbnLUB8fXaQh6d5WnQgk4Y',
    appId: '1:116767385787:web:7ced625d46203869e1e19e',
    messagingSenderId: '116767385787',
    projectId: 'k54-community',
    authDomain: 'k54-community.firebaseapp.com',
    storageBucket: 'k54-community.firebasestorage.app',
    measurementId: 'G-6Y7D2BB2PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhaKMc5bGWSdUa7ULNPH_O3z-Cu_Inj2g',
    appId: '1:116767385787:android:145e277ce6672bbbe1e19e',
    messagingSenderId: '116767385787',
    projectId: 'k54-community',
    storageBucket: 'k54-community.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWk4wGJ8VRtSpt8yp3sfZcz8N6T4zbXvA',
    appId: '1:116767385787:ios:f062b146d70d1e92e1e19e',
    messagingSenderId: '116767385787',
    projectId: 'k54-community',
    storageBucket: 'k54-community.firebasestorage.app',
    iosBundleId: 'com.example.k54Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWk4wGJ8VRtSpt8yp3sfZcz8N6T4zbXvA',
    appId: '1:116767385787:ios:f062b146d70d1e92e1e19e',
    messagingSenderId: '116767385787',
    projectId: 'k54-community',
    storageBucket: 'k54-community.firebasestorage.app',
    iosBundleId: 'com.example.k54Mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzpQKmHJ6bhvbnLUB8fXaQh6d5WnQgk4Y',
    appId: '1:116767385787:web:f636b29cd5a645b2e1e19e',
    messagingSenderId: '116767385787',
    projectId: 'k54-community',
    authDomain: 'k54-community.firebaseapp.com',
    storageBucket: 'k54-community.firebasestorage.app',
    measurementId: 'G-V6W2KKDG7C',
  );
}
